name: Add New Design
description: Select a design, implement it, and add it to the project.
title: "[Design]: "
labels: new-design
assignees:
  - erfansn
body:
  - type: markdown
    attributes:
      value: |
        Thank you for contributing to our project! Please fill out this form to propose a design you'd like to implement and add to the project.
        
        **Notice**
        Please update the title of this issue to include the design name & set the appropriate category name using labels (e.g. `food-category`)

  - type: input
    id: design_link
    attributes:
      label: Design Reference Link
      description: Provide the link to the design you have selected (e.g., from Dribbble, Behance, or another source).
      placeholder: e.g., https://dribbble.com/shots/example
    validations:
      required: true

  - type: textarea
    id: additional_notes
    attributes:
      label: Additional Notes
      description: Provide any other details about the design, such as interactions, animations, or specific requirements.
      placeholder: e.g., This design includes hover effects for buttons and should be responsive.
